### ISSUE TITLE
Failure to compile? 

### ISSUE THREAD

**Issue by devangel77b** [Lukemarino/Threaded-Serial-sailbot#1]
Lukemarino says: the compiler registers an error on "Thread thread;" and says Error: No default constructor exists for class "rtos::Thread"

**Comment by devangel77b** [comment]
I have been unable to recreate this error myself? Check what version of mbed-cli is being used? I am also unable to replicate the error using the online mbed compiler.

**Comment by Lukemarino** [comment]
Code now compiles
