### ISSUE TITLE
Pinmap not found for peripheral / fail to compile? 

### ISSUE THREAD

**Issue by devangel77b** [Lukemarino/Threaded-Serial-sailbot#2]
Lukemarino says:  When thread is commented out, the program will compile but the mbed will output the error: Mbed OS error : pinmap not found for peripheral We have double checked our pin asignments for the GPS and imu

**Comment by devangel77b** [comment]
I am unable to replicate this error using mbed-cli, mbed os 5.10.3, or online mbed compiler.

**Comment by Lukemarino** [comment]
Error caused by stand in code I had for the Spektrum reciever.
